### ISSUE TITLE
###

### ISSUE THREAD

**Issue by byrant9527** [TimoWilken/flappy-bird-pygame#4]

**Comment by TimoWilken** [comment]
Hello! I'm sorry, I don't speak Chinese and Google Translate only translates the issue title as "angry bird". Could you please be more specific?

**Comment by byrant9527** [comment]
Oh! I’m sorry. I do not fully understand how to use github. It’s a misunderstanding. Don’t care ,man

**Comment by TimoWilken** [comment]
OK, no worries!
